name: Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
          cache: true

      - name: Check out code
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          cd src/jara
          go mod tidy

      - name: Run unit tests
        run: |
          cd src/jara
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: src/jara/coverage.txt
          fail_ci_if_error: false
